Feature/cheatsheet snippets
Esri/arcgis-js-vscode-snippets pull request #43
Opened 2023-10-15 11:14 UTC by Estela-Ex

@hhkaos

2023-10-17 18:04 UTC, hhkaos requested changes
Good @Estela-Ex! I just made some comments and suggestions to your code.

2023-10-17 18:04 UTC, hhkaos commented on cheatsheet/main.js
> +  // outputElementBody.textContent = `${selectedData.body}`;
```suggestion
```

2023-10-17 18:04 UTC, hhkaos commented on cheatsheet/main.js
> +  while (generalSelector.firstChild) {
Same as previously: 

`generalSelector.innerHTML = '';`

2023-10-18 11:11 UTC, hhkaos commented
I also noticed if you don't add `text-wrap: wrap;`to `#output-body` in the CSS some script won't show properly. Example:
<img width="770" alt="Screenshot 2023-10-18 at 13 09 49" src="https://github.com/Esri/arcgis-js-vscode-snippets/assets/826965/ef70842f-3e33-432f-9a58-5b3550ab3604">

2023-10-21 06:02 UTC, hhkaos commented
@Estela-Ex with the last changes to master branch, this application breaks. I think the reason is:
* We have removed the `scss.json` file
* And some snippets `prefix` now contains an array instead of a string (e.g. [\["featureReductionClusterProps", "clusterConfig"\]](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/snippets/javascript.json#L226)). In these cases we should display the first element of the array. 

If you need any additional help, let me know.
Thanks!

2023-10-22 15:45 UTC, Estela-Ex commented
@hhkaos I did the request changes

2023-10-24 05:50 UTC, hhkaos approved these changes
LGTM

2023-10-24 05:52 UTC, merged

2023-10-24 07:15 UTC, hhkaos commented
Thank you very much for your contributions @Estela-Ex! This, I believe, will greatly help us in improving the documentation and use of this extension. I'm sure the entire user community appreciates the effort you've done! ❤️