feat: Add snippets for all Layer classes [#34]
Esri/arcgis-js-vscode-snippets pull request #63
Opened 2024-10-27 19:07 UTC by BochaberiDaisy

Fix: #34 

@hhkaos, please check the PR.

I have added snippets to all the Layers. 
Let me know if any changes are needed 🙂

2024-10-30 05:51 UTC, hhkaos requested changes
Hi @BochaberiDaisy ! Thank you very much for the PR. It is a great start and a lot of work, I really appreciate it. I have started checking and I have just noticed we need to review to meet the conventions. A few example I noticed so far:
* Prefixes in class constructors should match the Class Capitalization (e.g. `graphicsLayer` should be GraphicsLayer`; `addGeoRSSLayer` should be `GeoRSSLayer`, etc.). Prefixes starting with lowercase are used for class properties objects, common procedures, and enumerations. If you want to suggest a change, please check the issue #10.
* In the body I have seen inconsistencies with map.add(layerVariable) and not storing the variable. I don't have an strong opinion about having the statement or not, but if we add it, the layer variable should be instantiated within the snippet. If you want to suggest a change, please check the issue #19. 
* The descriptions are not following the conventions. Some descriptions are a little bit short. You can reuse text from the API reference. And the class initiatilization do not finish with the paths. 

I have added some comments just to illustrate some examples. 
Thanks again!

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "prefix": "csvLayer"
```suggestion
    "prefix": "CSVLayer"
```
Prefix on **Class constructors** should match the SDK capitalization according to [the conventions](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/CONTRIBUTING.md#prefix)

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "prefix": "csvLayerFromBlob"
```suggestion
    "prefix": "CSVLayerFromBlob"
```

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "prefix": "geoJSONLayer"
```suggestion
    "prefix": "GeoJSONLayer"
```

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "\tgeometry: ${1:point,polyline, polygon,}",
```suggestion
    "\tgeometry: ${1:Point,Polyline, Polygon}",
```

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "prefix": "addGeoRSSLayer"
```suggestion
    "prefix": "GeoRSSLayer"
```

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "map.add(graphicsLayer);",
```suggestion
```

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +        "table.load().then(function() {",
I feel this table load could be omited

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +        "\t\t\tname: \"${7:place}\",",
Probably we can remove this `place` field. It is redundant considering we have other "string field" already..

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +        "\tpopupTemplate: pTemplate,",
```suggestion
        "\tpopupTemplate: PopupTemplate,",
```

At some point we will introduce snippets for PopupTemplates too: https://github.com/Esri/arcgis-js-vscode-snippets/issues/64

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "description": "Add a CSVLayer with a URL",
```suggestion
    "description": "Add a CSVLayer (point layer) based on a CSV file (.csv, .txt) with a URL. CSV is a plain-text file format used to represent tabular data, including geographic point features (latitude, longitude). AMD path: esri/layers/CSVLayer | ESM path: @arcgis/core/layers/CSVLayer.js",
```
Following `description` [conventions](https://github.com/Esri/arcgis-js-vscode-snippets/blob/master/CONTRIBUTING.md#description)

2024-10-30 05:51 UTC, hhkaos commented on snippets/javascript.json
> +    "description": "Create and add a CSVLayer from a Blob object",
```suggestion
    "description": "Add a CSVLayer (point layer) based on a CSV file (.csv, .txt) from in-memory CSV data by passing a Blob object. AMD path: esri/layers/CSVLayer | ESM path: @arcgis/core/layers/CSVLayer.js",
```

2024-10-30 17:18 UTC, BochaberiDaisy commented
Here is the task list for the progress on the changes requested.

> * Vector layers
>   
>   * [x]  [CSVLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-CSVLayer.html#delimiter)
>   * [x]  [GeoJSONLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GeoJSONLayer.html)
>   * [x]  [GeoRSSLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GeoRSSLayer.html) (OGC)
>   * [x]  [GraphicsLayer](https://developers.arcgis.com/javascript/latest/add-a-point-line-and-polygon/)
>   * [ ]  [FeatureLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer/)
>   * [ ]  [FeatureLayer (client-side)](https://developers.arcgis.com/javascript/latest/layers-and-data/#client-side-data-sources)
>   * [ ]  [MapNotesLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-mapnoteslayer/)
>   * [x]  [OGCFeatureLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-ogcfeaturelayer/) OGC API - Features
>   * [ ]  [RouteLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-RouteLayer.html)
>   * [ ]  [StreamLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-streamlayer/)
>   * [ ]  [VectorTileLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-vectortilelayer/)
>   * [ ]  [WFSLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-wfs/) OGC Web Feature Service (WFS)
> * Raster Layers
>   
>   * [ ]  [ImageryTileLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-imagerylayer/)
>   * [ ]  [ImageryLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-imagerylayer/)
>   * [ ]  [ImageryTileLayer /w COG](https://developers.arcgis.com/javascript/latest/sample-code/layers-imagerytilelayer-cog/)
>   * [ ]  [ImageryTileLayer (Multidimensional)](https://developers.arcgis.com/javascript/latest/sample-code/layers-hosted-imagerytilelayer/)
>   * [ ]  [WebTileLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-WebTileLayer.html) - (XYZ layer / Slippy maps)
>   * [ ]  [WMSLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-wms/) OGC Web Map Service (WMS)
>   * [ ]  [WMTSLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-wmts/) OGC Web Map Tile Service (WMTS)
>   * [ ]  [WCSLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-WCSLayer.html) OGC Web Coverage Service (WCS)
>   * [ ]  [MapImageLayer (Time-based)](https://developers.arcgis.com/javascript/latest/sample-code/time-layer/) Traffic layer
>   * [ ]  [BingMapsLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-BingMapsLayer.html)
>   * [ ]  [OpenStreetMapLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-osm-3d/)
> * 3D layers
>   
>   * [ ]  [SceneLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-SceneLayer.html)
>   * [ ]  [Elevation](https://developers.arcgis.com/javascript/latest/sample-code/scene-elevationlayer/)
>   * [ ]  [PointCloud](https://developers.arcgis.com/javascript/latest/sample-code/layers-pointcloud-portal/)
>   * [ ]  [BuildingSceneLayer](https://developers.arcgis.com/javascript/latest/sample-code/building-scene-layer-slice/)
>   * [ ]  [LineOfSightLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-LineOfSightLayer.html)
>   * [ ]  [DimensionLayer](https://developers.arcgis.com/javascript/latest/sample-code/layers-dimension/)
>   * [ ]  [IntegratedMeshLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-IntegratedMeshLayer.html)
>   * [ ]  [VoxelLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-VoxelLayer.html)
> * Others
>   
>   * [ ]  [MediaLayers](https://developers.arcgis.com/javascript/latest/sample-code/layers-medialayer-control-points/) (Overlayed images with control points)
>   * [ ]  [MediaLayers (/w video)](https://developers.arcgis.com/javascript/latest/sample-code/layers-medialayer-video/)
>   * [ ]  [KML Layer](https://developers.arcgis.com/javascript/latest/sample-code/layers-kml/) (OGC)
>   * [ ]  [GroupLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GroupLayer.html)
>   * [ ]  [SubtypeGroupLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-SubtypeGroupLayer.html)
>   * [ ]  [TileLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-ImageryTileLayer.html)
>   * [ ]  [KnowledgeGraphLayer](https://developers.arcgis.com/javascript/latest/sample-code/knowledgegraph-knowledgegraphlayer/)

2024-10-31 15:53 UTC, hhkaos requested changes
Amazing work @BochaberiDaisy ! 👏 😍

I just added a few minor things. And I would say just make sure to prettify (fix all indentations).

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +        "\t\t\tname: \"${10:recordedDate}\",",
The order should be updated. It's jumping from 6 to 10

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +  "Load WebMap with MapNotes Layer": {
```suggestion
  "Load MapNotes Layer": {
```

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +    "const mapNotesLayer = new MapNotesLayer({",
```suggestion
    "new MapNotesLayer({",
```

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +      "prefix": "routeLayer"
```suggestion
      "prefix": "RouteLayer"
```

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +  "Add Vector Tile Layer": {
Constructing the vector tile using the style object is OK, but pretty unusual.  I would add [the usual one](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-VectorTileLayer.html#esri/layers/VectorTileLayer):

```js
new VectorTileLayer({
  url: "https://www.arcgis.com/sharing/rest/content/items/4cf7e1fb9f254dcda9c8fbadb15cf0f8/resources/styles/root.json"
});
```

And maybe:
```js
const layer = new VectorTileLayer({
 portalItem:{
   id: "1c365daf37a744fbad748b67aa69dac8"
 }
});
```

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +    "});"
```suggestion
    "});",
    "await wmsLayer.load();"
```
If I remember correctly, in this case, calling load() is important.
Understanding the loadable [pattern](https://developers.arcgis.com/javascript/latest/loadable/)

2024-10-31 15:53 UTC, hhkaos commented on snippets/javascript.json
> +      "description": "Add a OpenStreetMapLayer to the map. OpenStreetMapLayer allows the use basemaps from OpenStreetMap. AMD path: esri/layers/OpenStreetMapLayer | ESM path: @arcgis/core/layers/Open
```suggestion
      "description": "Add an OpenStreetMapLayer to the map served. Tiles are served from tile.openstreetmap.org. OpenStreetMapLayer allows the use basemaps from OpenStreetMap. AMD path: esri/layers/OpenStreetMapLayer | ESM path: @arcgis/core/layers/OpenStreetMapLayer.js",
```

2024-10-31 15:53 UTC, hhkaos requested changes
Amazing work @BochaberiDaisy ! 👏 😍

I just added a few minor things. And I would say just make sure to prettify (fix all indentations).

2024-10-31 18:10 UTC, BochaberiDaisy commented
@hhkaos, I have pushed the requested changes. Please check it out.

Thank you for the feedback!

2024-10-31 19:20 UTC, hhkaos approved these changes
Awesome work @BochaberiDaisy , it looks good to me, thank you very much for the hard work!

2024-10-31 19:20 UTC, merged